version: "3.8"

name: "test_service_interconnection"

networks:
  test-network:
    driver: bridge

services:
  test1:
    build:
      context: /test1
      dockerfile: Dockerfile
    container_name: test1
    image: test1:latest
    ports:
      - "1234:8080"
    networks:
      - test-network

  test2:
    build:
      context: /test2
      dockerfile: Dockerfile
    container_name: test2
    image: test2:latest
    ports:
      - "4321:8080"
    networks:
      - test-network